// generated by stringer -type stateT; DO NOT EDIT

package life

import "fmt"

const _stateT_name = "InitingStartingRunningShutingdownhalt"

var _stateT_index = [...]uint8{0, 7, 15, 22, 33, 37}

func (i StateT) String() string {
	if i < 0 || i+1 >= StateT(len(_stateT_index)) {
		return fmt.Sprintf("stateT(%d)", i)
	}
	return _stateT_name[_stateT_index[i]:_stateT_index[i+1]]
}
