// generated by stringer -type stateT; DO NOT EDIT

package life

import "fmt"

const _stateT_name = "initingstartingrunningshutdown"

var _stateT_index = [...]uint8{0, 7, 15, 22, 30}

func (i stateT) String() string {
	if i < 0 || i+1 >= stateT(len(_stateT_index)) {
		return fmt.Sprintf("stateT(%d)", i)
	}
	return _stateT_name[_stateT_index[i]:_stateT_index[i+1]]
}
